### PR TITLE
Jim edits

### PR DESCRIPTION
**Pull request by Megalithicireland**
Alterations to icons and index

### CODE REVIEW

**Comment by mro** [comment]
mind that your changes won't make it to https://megalithicirelandmap.github.io until you merge them into the 'master' branch.

**Comment by Megalithicireland** [comment]
Hi Marcus
I have merged the changes and can view them on the map. I added the new
icons and altered some of the names in the monuments gpx. I am doing them
to the master. I had a problem trying to add description to them at the end
of each gpx file ie. Sym standingstones Sym. I could alter  one from abbeys
to church but not add a sym where one was needed.
Hope this makes sense to you lol
Jim

**Comment by mro** [comment]
awesome, I see you're making yourself familiar.

> but not add a sym where one was needed

I saw the edit dbc5c82b1b93 where you made a typo – I think you intended `<sym>subject#standingstones</sym>` (mind the opening tag has no /).

**Comment by mro** [comment]
P.S.: I use both, a plain text-editor as well as a dedicated GPX editing tool (https://itunes.apple.com/ie/app/gpx-editor/id924782627) to work with the gpx.

The `<description>` which is displayed in the callout bubble on each item is a bit hairy, because it contains html in escaped form, so `<a href="foo&bar">` must be written as `&lt;a href=&quot;foo&amp;bar&quot;&gt;`

We can either
1. keep the escaped form (which looks a bit odd nd isn't easily human readable when editing),
2. change to `<![CDATA[ <a href="foo&bar"> ]]>` (which looks a little bit less odd) or
3. change the data loading to build the description automatically from what the `<link>` and `<name>` contains. (which requires a bit of JavaScript hacking but is feasible)

**Comment by Megalithicireland** [comment]
Marcus, this is still above my head but I am slowly coming around. I don't
actually write any code. I just compare against the other gpx and copy and
paste to make changes where needed for it to work. I used the <sym/> that
was already there and cut and pasted the the rest from another gpx file. I
see now that i should have deleted / out of the opening tag. That one typo
made all the icons disappear lol.
I will have to learn how to scrape a file and add it to the monuments.gpx
Thanks for your patience
Jim

**Comment by mro** [comment]
> … this is still above my head but I am slowly coming around. I don't
> actually write any code. I just compare against the other gpx and copy and
> paste to make changes where needed for it to work. I used the <sym/> that
> was already there and cut and pasted the the rest from another gpx file. I
> see now that i should have deleted / out of the opening tag. That one typo
> made all the icons disappear lol.
> I will have to learn how to scrape a file and add it to the monuments.gpx
> Thanks for your patience

you’re welcome and you’re doing very well I think. Take it slowly, edit recklessly and tell me any inconveniences you experience.

What I wanted to say is, that the callout-bubble content of each item (see Screenshot ) comes from the <desc> in the gpx. In the screenshot's case it’s

```
<desc>&lt;a href="http://megalithicireland.com/Trawbaun%20Medieval%20Church.html?src=gpx"&gt;@megalithicireland.com&lt;/a&gt;</desc>
```

which is a html snippet wrapped so the it can go into an xml file. Imagine transporting beer across a lake – better ‚wrap' the beer in a barrel or bottle but just spilling it into the water. The un-wrapped html of the above is:

```
<a href="http://megalithicireland.com/Trawbaun%20Medieval%20Church.html?src=gpx“>@megalithicireland.com</a>
```

and that’s what the content of the callout-bubble looks like. If editing the <desc> in its current way is to inconvenient, there’s the 3 alternatives I mentioned briefly.

Cheers and happy megalithing,

```
Marcus
```

> > We can either
> > 1. keep the escaped form (which looks a bit odd nd isn't easily human
> >    readable when editing),
> > 2. change to <![CDATA[ <a href="foo&bar"> ]]> (which looks a little
> >    bit less odd) or
> > 3. change the data loading to build the description automatically from
> >    what the <link> and <name> contains. (which requires a bit of
> >    JavaScript hacking but is feasible)

**Comment by Megalithicireland** [comment]
Thanks again Marcus. I don't mind editing the bubble manually.

**Pull request merged**
